name: Maven
description: Ultimate workout tracking app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:

    sdk: flutter


  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  theme_provider: ^0.5.0
  sqflite: ^2.2.2
  path_provider: ^2.0.11
  provider: ^6.0.5
  settings_ui: ^2.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  extended_sliver: ^2.1.3
  expandable: ^5.0.1
  drag_and_drop_lists: ^0.3.3
  cupertino_icons: ^1.0.5
  timeago: ^3.3.0
  sliding_up_panel: ^2.0.0+1
  percent_indicator: ^4.2.2
  floor: ^1.4.1
  floor_generator: ^1.4.1
  build_runner: ^2.3.3
  flutter_shake_animated: ^0.0.5
  flutter_colorpicker: ^1.0.3
  audioplayers: ^3.0.1
  audioplayers_linux: ^1.0.4
  flutter_swipe_action_cell: ^3.1.0
  reorderables: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/
    - assets/squat.png
flutter_intl:
  enabled: false
